### ISSUE TITLE
Payubiz india

### ISSUE THREAD

**Issue by manojurfriend** [ORBA/magento2_payupl#1]
can we use the sam plugin for payubiz india magento integration ??

**Comment by supriyaamisshra** [comment]
Hi Manoj,
Did you find it suitablle for Payubiz in magento 2.0.7 ??

**Comment by michalbiarda** [comment]
Hi Manoj,

Sorry for late reply. I didn't notice your comment until SupriyaVashishthaMishra wrote his.
I'm pretty sure the plugin won't work with other Payu than Polish, but I guess the APIs are similar so maybe you could try to overwrite our module a bit instead of writing new one from scratch.

Regards,
Michał

**Comment by djyoti07** [comment]
Hi Manoj,
Did you succeed overwriting this module to work with PayUBiz India?
Regards,
Deep

**Comment by supriyaamisshra** [comment]
Yes!! Implemented

**Comment by djyoti07** [comment]
Hi Supriya,
Can you please help me to get this extension?
Thanls

**Comment by chinthu** [comment]
Hi Supriya,
Can you please help me to get payuBiz overritten extension 
Thanks

**Comment by djyoti07** [comment]
Hi @chinthu we can provide you a premium extension at reasonable price. (Skype: deep.bhuyan84)
