### ISSUE TITLE
Currency problem.

### ISSUE THREAD

**Issue by mosiolekdamian** [ORBA/magento2_payupl#4]
Hi!
Whenever I am trying to use your extension as a payment method in my store i have a problem with currencies.
My store is in EURO and when client start doing chekout using PAY U as a payment method it redirects him to the PAY U site but the total in PLN = total in EURO.
So for example device should cost 2000EUR but when using PAY U after redirecting to the PAU site it is 2000 PLN.
Do you have any idea how i can fix this problem?
I'm using classic POS.
THANKS

**Comment by Talv** [comment]
I believe only `classic` POS is affected, in which case the information about currency is not passed to the POS at all. The `non-classic` POS based on REST API might handle such case correctly.

I've made a hotfix for `classic` POS:
https://github.com/ORBA/magento2_payupl/blob/c04f293406d520e58cdb8c2d9c5ee68e24419378/Model/Client/Classic/Order/DataGetter.php#L57
```diff
         $incrementId = $order->getIncrementId();
         $billingAddress = $order->getBillingAddress();
         $data = [
-            'amount' => $order->getGrandTotal() * 100,
+            'amount' => $order->getBaseGrandTotal() * 100,
             'desc' => __('Order # %1', [$incrementId]),
             'desc2' => 'Orba_Payupl_M2',
             'first_name' => $billingAddress->getFirstname(),
```
But it will work only if your base currency is PLN.

As a long term solution I recommend switching to https://github.com/PayU/plugin_magento_2

**Comment by michalbiarda** [comment]
Hi @mosiolekdamian 

I'm very sorry for replying sooo late. We lost focus of this extension for a long time but now we're coming back to ongoing development.

Unfortunately "Classic" POS doesn't allow specifying currency. If you want to collect payments in EUR using "Classic" POS, you need to configure your store on Payu.pl side to accept EUR instead of PLN. This might require signing additional documents with them.
